{{ if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "rota-slackbot.fullname" . }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
  rules:
    - host: {{ required "A valid ingress hostname entry required!" .Values.ingress.hostname }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: {{ include "rota-slackbot.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end -}}