apiVersion: v2
name: rota-slackbot
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "0.1.0"

dependencies:
  - name: mongodb
    condition: mongodb.enabled
    version: 10.29.2
    repository: https://charts.bitnami.com/bitnami
